#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Minesweeper.Resource", IsApplication=true)]

namespace Minesweeper
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Minesweeper.Logic.Resource.String.ApplicationName = global::Minesweeper.Resource.String.ApplicationName;
			global::Minesweeper.Logic.Resource.String.Hello = global::Minesweeper.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AtSea = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int MineExplosion = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RadarSweep = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int BackButton = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int DisplayFieldButton = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int ExitButton = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int MainLinearLayout = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int NewGameButton = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int NumberOfColumns = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int NumberOfMines = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int NumberOfRows = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int PlayButton = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int SettingsApplyButton = 2131034128;
			
			// aapt resource value: 0x7f050001
			public const int SettingsButton = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int SettingsCancelButton = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout2 = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout3 = 2131034124;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout4 = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int textView2 = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int textView3 = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Play = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PlayingFieldItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int ActivityTextPlay = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ActivityTextSettings = 2130968586;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int Boom = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int ButtonTextApply = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int ButtonTextBack = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int ButtonTextCancel = 2130968589;
			
			// aapt resource value: 0x7f040012
			public const int ButtonTextExit = 2130968594;
			
			// aapt resource value: 0x7f04000e
			public const int ButtonTextHint = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int ButtonTextNewGame = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int ButtonTextPlay = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int ButtonTextSettings = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Settings = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SettingsNumberOfColumns = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SettingsNumberOfRows = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int TextNumberOfColumns = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int TextNumberOfMines = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int TextNumberOfRows = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int app_name = 2130968595;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
